[package]
description = "Apache OpenDAL™'s OpenVAL: One Layer, All Vectors."
name = "openval"

authors = ["Apache OpenDAL <dev@opendal.apache.org>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/apache/opendal"
rust-version = "1.85"
version = "0.0.0"

[dependencies]
