# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

class Capability:
    r"""
    Capability defines the supported operations and their constraints for a storage Operator.

    This structure provides a comprehensive description of an Operator's
    capabilities, including:

    - Basic operations support (read, write, delete, etc.)
    - Advanced operation variants (conditional operations, metadata handling)
    - Operational constraints (size limits, batch limitations)
    """

    @property
    def stat(self) -> builtins.bool:
        r"""If operator supports stat."""
    @property
    def stat_with_if_match(self) -> builtins.bool:
        r"""If operator supports stat with if match."""
    @property
    def stat_with_if_none_match(self) -> builtins.bool:
        r"""If operator supports stat with if none match."""
    @property
    def read(self) -> builtins.bool:
        r"""Indicates if the operator supports read operations."""
    @property
    def read_with_if_match(self) -> builtins.bool:
        r"""Indicates if conditional read operations using If-Match are supported."""
    @property
    def read_with_if_none_match(self) -> builtins.bool:
        r"""Indicates if conditional read operations using If-None-Match are supported."""
    @property
    def read_with_if_modified_since(self) -> builtins.bool:
        r"""Indicates if conditional read operations using If-Modified-Since are supported."""
    @property
    def read_with_if_unmodified_since(self) -> builtins.bool:
        r"""Indicates if conditional read operations using If-Unmodified-Since are supported."""
    @property
    def read_with_override_cache_control(self) -> builtins.bool:
        r"""Indicates if Cache-Control header override is supported during read operations."""
    @property
    def read_with_override_content_disposition(self) -> builtins.bool:
        r"""Indicates if Content-Disposition header override is supported during read operations."""
    @property
    def read_with_override_content_type(self) -> builtins.bool:
        r"""Indicates if Content-Type header override is supported during read operations."""
    @property
    def read_with_version(self) -> builtins.bool:
        r"""Indicates if versions read operations are supported."""
    @property
    def write(self) -> builtins.bool:
        r"""Indicates if the operator supports write operations."""
    @property
    def write_can_multi(self) -> builtins.bool:
        r"""Indicates if multiple write operations can be performed on the same object."""
    @property
    def write_can_empty(self) -> builtins.bool:
        r"""Indicates if writing empty content is supported."""
    @property
    def write_can_append(self) -> builtins.bool:
        r"""Indicates if append operations are supported."""
    @property
    def write_with_content_type(self) -> builtins.bool:
        r"""Indicates if Content-Type can be specified during write operations."""
    @property
    def write_with_content_disposition(self) -> builtins.bool:
        r"""Indicates if Content-Disposition can be specified during write operations."""
    @property
    def write_with_content_encoding(self) -> builtins.bool:
        r"""Indicates if Content-Encoding can be specified during write operations."""
    @property
    def write_with_cache_control(self) -> builtins.bool:
        r"""Indicates if Cache-Control can be specified during write operations."""
    @property
    def write_with_if_match(self) -> builtins.bool:
        r"""Indicates if conditional write operations using If-Match are supported."""
    @property
    def write_with_if_none_match(self) -> builtins.bool:
        r"""Indicates if conditional write operations using If-None-Match are supported."""
    @property
    def write_with_if_not_exists(self) -> builtins.bool:
        r"""Indicates if write operations can be conditional on object non-existence."""
    @property
    def write_with_user_metadata(self) -> builtins.bool:
        r"""Indicates if custom user metadata can be attached during write operations."""
    @property
    def write_multi_max_size(self) -> builtins.int | None:
        r"""
        Maximum size supported for multipart uploads.

        For example, AWS S3 supports up to 5GiB per part in multipart uploads.
        """
    @property
    def write_multi_min_size(self) -> builtins.int | None:
        r"""
        Minimum size required for multipart uploads (except for the last part).

        For example, AWS S3 requires at least 5MiB per part.
        """
    @property
    def write_total_max_size(self) -> builtins.int | None:
        r"""
        Maximum total size supported for write operations.

        For example, Cloudflare D1 has a 1MB total size limit.
        """
    @property
    def create_dir(self) -> builtins.bool:
        r"""If operator supports create dir."""
    @property
    def delete(self) -> builtins.bool:
        r"""If operator supports delete."""
    @property
    def copy(self) -> builtins.bool:
        r"""If operator supports copy."""
    @property
    def rename(self) -> builtins.bool:
        r"""If operator supports rename."""
    @property
    def list(self) -> builtins.bool:
        r"""If operator supports list."""
    @property
    def list_with_limit(self) -> builtins.bool:
        r"""If backend supports list with limit."""
    @property
    def list_with_start_after(self) -> builtins.bool:
        r"""If backend supports list with start after."""
    @property
    def list_with_recursive(self) -> builtins.bool:
        r"""If backend supports list without delimiter."""
    @property
    def presign(self) -> builtins.bool:
        r"""If operator supports presign."""
    @property
    def presign_read(self) -> builtins.bool:
        r"""If operator supports presign read."""
    @property
    def presign_stat(self) -> builtins.bool:
        r"""If operator supports presign stat."""
    @property
    def presign_write(self) -> builtins.bool:
        r"""If operator supports presign write."""
    @property
    def presign_delete(self) -> builtins.bool:
        r"""If operator supports presign delete."""
    @property
    def shared(self) -> builtins.bool:
        r"""If operator supports shared."""
