# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

class AlreadyExists(builtins.BaseException):
    r"""Already exists."""

class ConditionNotMatch(builtins.BaseException):
    r"""Condition not match."""

class ConfigInvalid(builtins.BaseException):
    r"""Config is invalid."""

class Error(builtins.BaseException):
    r"""OpenDAL Base Exception."""

class IsADirectory(builtins.BaseException):
    r"""Is a directory."""

class IsSameFile(builtins.BaseException):
    r"""Is same file."""

class NotADirectory(builtins.BaseException):
    r"""Not a directory."""

class NotFound(builtins.BaseException):
    r"""Not found."""

class PermissionDenied(builtins.BaseException):
    r"""Permission denied."""

class Unexpected(builtins.BaseException):
    r"""Unexpected errors."""

class Unsupported(builtins.BaseException):
    r"""Unsupported operation."""
