# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import collections.abc
import datetime
import os
import pathlib
import typing

import typing_extensions

import opendal.file
import opendal.services
import opendal.types
from opendal.capability import Capability
from opendal.file import File
from opendal.layers import Layer
from opendal.types import Metadata

@typing.final
class AsyncOperator:
    r"""
    The async equivalent of `Operator`.

    `AsyncOperator` is the entry point for all async APIs.

    See Also
    --------
    Operator
    """

    def layer(self, layer: Layer) -> AsyncOperator:
        r"""
        Add a new layer to the operator.

        Parameters
        ----------
        layer : Layer
            The layer to add.

        Returns
        -------
        AsyncOperator
            A new operator with the layer added.
        """
    def open(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        mode: builtins.str,
        **kwargs: typing.Any,
    ) -> collections.abc.Awaitable[opendal.file.AsyncFile]:
        r"""
        Open an async file-like object for the given path.

        The returning async file-like object is a context manager.

        Parameters
        ----------
        path : str
            The path to the file.
        mode : str
            The mode to open the file in. Only "rb" and "wb" are supported.
        **kwargs : dict
            Additional options for the underlying reader or writer.

        Returns
        -------
        coroutine
            An awaitable that returns a file-like object.
        """
    def read(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        *,
        version: builtins.str | None = None,
        concurrent: builtins.int | None = None,
        chunk: builtins.int | None = None,
        gap: builtins.int | None = None,
        offset: builtins.int | None = None,
        prefetch: builtins.int | None = None,
        size: builtins.int | None = None,
        if_match: builtins.str | None = None,
        if_none_match: builtins.str | None = None,
        if_modified_since: datetime.datetime = None,
        if_unmodified_since: datetime.datetime = None,
        content_type: builtins.str | None = None,
        cache_control: builtins.str | None = None,
        content_disposition: builtins.str | None = None,
    ) -> collections.abc.Awaitable[builtins.bytes]:
        r"""
        Read the entire contents of a file at the given path.

        Parameters
        ----------
        path : str
            The path to the file.
        version : str, optional
            The version of the file.
        concurrent : int, optional
            The number of concurrent readers.
        chunk : int, optional
            The size of each chunk.
        gap : int, optional
            The gap between each chunk.
        offset : int, optional
            The offset of the file.
        prefetch : int, optional
            The number of bytes to prefetch.
        size : int, optional
            The size of the file.
        if_match : str, optional
            The ETag of the file.
        if_none_match : str, optional
            The ETag of the file.
        if_modified_since : str, optional
            The last modified time of the file.
        if_unmodified_since : str, optional
            The last modified time of the file.
        content_type : str, optional
            The content type of the file.
        cache_control : str, optional
            The cache control of the file.
        content_disposition : str, optional
            The content disposition of the file.

        Returns
        -------
        coroutine
            An awaitable that returns the contents of the file as bytes.
        """
    def write(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        bs: builtins.bytes,
        *,
        append: builtins.bool | None = None,
        chunk: builtins.int | None = None,
        concurrent: builtins.int | None = None,
        cache_control: builtins.str | None = None,
        content_type: builtins.str | None = None,
        content_disposition: builtins.str | None = None,
        content_encoding: builtins.str | None = None,
        if_match: builtins.str | None = None,
        if_none_match: builtins.str | None = None,
        if_not_exists: builtins.bool | None = None,
        user_metadata: typing.Mapping[builtins.str, builtins.str] | None = None,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Write bytes to a file at the given path.

        This function will create a file if it does not exist, and will
        overwrite its contents if it does.

        Parameters
        ----------
        path : str
            The path to the file.
        bs : bytes
            The contents to write to the file.
        append : bool, optional
            Whether to append to the file instead of overwriting it.
        chunk : int, optional
            The chunk size to use when writing the file.
        concurrent : int, optional
            The number of concurrent requests to make when writing the file.
        cache_control : str, optional
            The cache control header to set on the file.
        content_type : str, optional
            The content type header to set on the file.
        content_disposition : str, optional
            The content disposition header to set on the file.
        content_encoding : str, optional
            The content encoding header to set on the file.
        if_match : str, optional
            The ETag to match when writing the file.
        if_none_match : str, optional
            The ETag to not match when writing the file.
        if_not_exists : bool, optional
            Whether to fail if the file already exists.
        user_metadata : dict, optional
            The user metadata to set on the file.

        Returns
        -------
        coroutine
            An awaitable that completes when the write is finished.
        """
    def stat(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        *,
        version: builtins.str | None = None,
        if_match: builtins.str | None = None,
        if_none_match: builtins.str | None = None,
        if_modified_since: datetime.datetime = None,
        if_unmodified_since: datetime.datetime = None,
        content_type: builtins.str | None = None,
        cache_control: builtins.str | None = None,
        content_disposition: builtins.str | None = None,
    ) -> collections.abc.Awaitable[Metadata]:
        r"""
        Get the metadata of a file at the given path.

        Parameters
        ----------
        path : str
            The path to the file.
        version : str, optional
            The version of the file.
        if_match : str, optional
            The ETag of the file.
        if_none_match : str, optional
            The ETag of the file.
        if_modified_since : datetime, optional
            The last modified time of the file.
        if_unmodified_since : datetime, optional
            The last modified time of the file.
        content_type : str, optional
            The content type of the file.
        cache_control : str, optional
            The cache control of the file.
        content_disposition : str, optional
            The content disposition of the file.

        Returns
        -------
        coroutine
            An awaitable that returns the metadata of the file.
        """
    def copy(
        self,
        source: builtins.str | os.PathLike | pathlib.Path,
        target: builtins.str | os.PathLike | pathlib.Path,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Copy a file from one path to another.

        Parameters
        ----------
        source : str
            The path to the source file.
        target : str
            The path to the target file.

        Returns
        -------
        coroutine
            An awaitable that completes when the copy is finished.
        """
    def rename(
        self,
        source: builtins.str | os.PathLike | pathlib.Path,
        target: builtins.str | os.PathLike | pathlib.Path,
    ) -> collections.abc.Awaitable[None]:
        r"""
        Rename (move) a file from one path to another.

        Parameters
        ----------
        source : str
            The path to the source file.
        target : str
            The path to the target file.

        Returns
        -------
        coroutine
            An awaitable that completes when the rename is finished.
        """
    def remove_all(
        self, path: builtins.str | os.PathLike | pathlib.Path
    ) -> collections.abc.Awaitable[None]:
        r"""
        Recursively remove all files and directories at the given path.

        Parameters
        ----------
        path : str
            The path to remove.

        Returns
        -------
        coroutine
            An awaitable that completes when the removal is finished.
        """
    def check(self) -> collections.abc.Awaitable[None]:
        r"""
        Check if the operator is able to work correctly.

        Returns
        -------
        coroutine
            An awaitable that completes when the check is finished.

        Raises
        ------
        Exception
            If the operator is not able to work correctly.
        """
    def create_dir(
        self, path: builtins.str | os.PathLike | pathlib.Path
    ) -> collections.abc.Awaitable[None]:
        r"""
        Create a directory at the given path.

        Notes
        -----
        To indicate that a path is a directory, it must end with a `/`.
        This operation is always recursive, like `mkdir -p`.

        Parameters
        ----------
        path : str
            The path to the directory.

        Returns
        -------
        coroutine
            An awaitable that completes when the directory is created.
        """
    def delete(
        self, path: builtins.str | os.PathLike | pathlib.Path
    ) -> collections.abc.Awaitable[None]:
        r"""
        Delete a file at the given path.

        Notes
        -----
        This operation will not return an error if the path does not exist.

        Parameters
        ----------
        path : str
            The path to the file.

        Returns
        -------
        coroutine
            An awaitable that completes when the file is deleted.
        """
    def exists(
        self, path: builtins.str | os.PathLike | pathlib.Path
    ) -> collections.abc.Awaitable[builtins.bool]:
        r"""
        Check if a path exists.

        Parameters
        ----------
        path : str
            The path to check.

        Returns
        -------
        coroutine
            An awaitable that returns True if the path exists, False otherwise.
        """
    def list(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        *,
        limit: builtins.int | None = None,
        start_after: builtins.str | None = None,
        recursive: builtins.bool | None = None,
        versions: builtins.bool | None = None,
        deleted: builtins.bool | None = None,
    ) -> collections.abc.Awaitable[collections.abc.AsyncIterable[opendal.types.Entry]]:
        r"""
        List entries in the given directory.

        Parameters
        ----------
        path : str
            The path to the directory.
        limit : int, optional
            The maximum number of entries to return.
        start_after : str, optional
            The entry to start after.
        recursive : bool, optional
            Whether to list recursively.
        versions : bool, optional
            Whether to list versions.
        deleted : bool, optional
            Whether to list deleted entries.

        Returns
        -------
        coroutine
            An awaitable that returns an async iterator over the entries.
        """
    def presign_stat(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        expire_second: builtins.int,
    ) -> collections.abc.Awaitable[opendal.types.PresignedRequest]:
        r"""
        Create a presigned request for a stat operation.

        Parameters
        ----------
        path : str
            The path of the object to stat.
        expire_second : int
            The number of seconds until the presigned URL expires.

        Returns
        -------
        coroutine
            An awaitable that returns a presigned request object.
        """
    def presign_read(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        expire_second: builtins.int,
    ) -> collections.abc.Awaitable[opendal.types.PresignedRequest]:
        r"""
        Create a presigned request for a read operation.

        Parameters
        ----------
        path : str
            The path of the object to read.
        expire_second : int
            The number of seconds until the presigned URL expires.

        Returns
        -------
        coroutine
            An awaitable that returns a presigned request object.
        """
    def presign_write(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        expire_second: builtins.int,
    ) -> collections.abc.Awaitable[opendal.types.PresignedRequest]:
        r"""
        Create a presigned request for a write operation.

        Parameters
        ----------
        path : str
            The path of the object to write to.
        expire_second : int
            The number of seconds until the presigned URL expires.

        Returns
        -------
        coroutine
            An awaitable that returns a presigned request object.
        """
    def presign_delete(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        expire_second: builtins.int,
    ) -> collections.abc.Awaitable[opendal.types.PresignedRequest]:
        r"""
        Create a presigned request for a delete operation.

        Parameters
        ----------
        path : str
            The path of the object to delete.
        expire_second : int
            The number of seconds until the presigned URL expires.

        Returns
        -------
        coroutine
            An awaitable that returns a presigned request object.
        """
    def capability(self) -> Capability:
        r"""
        Get all capabilities of this operator.

        Returns
        -------
        Capability
            The capability of the operator.
        """
    def to_operator(self) -> Operator:
        r"""
        Create a new blocking `Operator` from this async operator.

        Returns
        -------
        Operator
            The blocking operator.
        """
    @typing.overload
    def __new__(
        cls, scheme: builtins.str, /, **kwargs: builtins.str
    ) -> typing_extensions.Self: ...
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Gdrive | typing.Literal["gdrive"],
        /,
        *,
        access_token: builtins.str = ...,
        client_id: builtins.str = ...,
        client_secret: builtins.str = ...,
        refresh_token: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `gdrive` service.

        Parameters
        ----------
        access_token : builtins.str, optional
            Access token for gdrive.
        client_id : builtins.str, optional
            Client id for gdrive.
        client_secret : builtins.str, optional
            Client secret for gdrive.
        refresh_token : builtins.str, optional
            Refresh token for gdrive.
        root : builtins.str, optional
            The root for gdrive

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `gdrive` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Gridfs | typing.Literal["gridfs"],
        /,
        *,
        bucket: builtins.str = ...,
        chunk_size: builtins.int = ...,
        connection_string: builtins.str = ...,
        database: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `gridfs` service.

        Parameters
        ----------
        bucket : builtins.str, optional
            The bucket name of the MongoDB GridFs service to
            read/write.
        chunk_size : builtins.int, optional
            The chunk size of the MongoDB GridFs service used to
            break the user file into chunks.
        connection_string : builtins.str, optional
            The connection string of the MongoDB service.
        database : builtins.str, optional
            The database name of the MongoDB GridFs service to
            read/write.
        root : builtins.str, optional
            The working directory, all operations will be
            performed under it.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `gridfs` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Http | typing.Literal["http"],
        /,
        *,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        root: builtins.str = ...,
        token: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `http` service.

        Parameters
        ----------
        endpoint : builtins.str, optional
            endpoint of this backend
        password : builtins.str, optional
            password of this backend
        root : builtins.str, optional
            root of this backend
        token : builtins.str, optional
            token of this backend
        username : builtins.str, optional
            username of this backend

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `http` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Ipmfs | typing.Literal["ipmfs"],
        /,
        *,
        endpoint: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `ipmfs` service.

        Parameters
        ----------
        endpoint : builtins.str, optional
            Endpoint for ipfs.
        root : builtins.str, optional
            Root for ipfs.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `ipmfs` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Memory | typing.Literal["memory"],
        /,
        *,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `memory` service.

        Parameters
        ----------
        root : builtins.str, optional
            root of the backend.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `memory` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Mongodb | typing.Literal["mongodb"],
        /,
        *,
        collection: builtins.str = ...,
        connection_string: builtins.str = ...,
        database: builtins.str = ...,
        key_field: builtins.str = ...,
        root: builtins.str = ...,
        value_field: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `mongodb` service.

        Parameters
        ----------
        collection : builtins.str, optional
            collection of this backend
        connection_string : builtins.str, optional
            connection string of this backend
        database : builtins.str, optional
            database of this backend
        key_field : builtins.str, optional
            key field of this backend
        root : builtins.str, optional
            root of this backend
        value_field : builtins.str, optional
            value field of this backend

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `mongodb` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Onedrive | typing.Literal["onedrive"],
        /,
        *,
        access_token: builtins.str = ...,
        client_id: builtins.str = ...,
        client_secret: builtins.str = ...,
        enable_versioning: builtins.bool = ...,
        refresh_token: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `onedrive` service.

        Parameters
        ----------
        access_token : builtins.str, optional
            Microsoft Graph API (also OneDrive API) access token
        client_id : builtins.str, optional
            Microsoft Graph API Application (client) ID that is
            in the Azure's app registration portal
        client_secret : builtins.str, optional
            Microsoft Graph API Application client secret that
            is in the Azure's app registration portal
        enable_versioning : builtins.bool, optional
            Enabling version support
        refresh_token : builtins.str, optional
            Microsoft Graph API (also OneDrive API) refresh
            token
        root : builtins.str, optional
            The root path for the OneDrive service for the file
            access

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `onedrive` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Redis | typing.Literal["redis"],
        /,
        *,
        cluster_endpoints: builtins.str = ...,
        connection_pool_max_size: builtins.int = ...,
        db: builtins.int,
        default_ttl: typing.Any = ...,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        root: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `redis` service.

        Parameters
        ----------
        cluster_endpoints : builtins.str, optional
            network address of the Redis cluster service.
            Can be
            "tcp://127.0.0.1:6379,tcp://127.0.0.1:6380,tcp://127.0.0.1:6381",
            e.g.
            default is None
        connection_pool_max_size : builtins.int, optional
            The maximum number of connections allowed.
            default is 10
        db : builtins.int
            the number of DBs redis can take is unlimited
            default is db 0
        default_ttl : typing.Any, optional
            The default ttl for put operations..
            a human readable duration string see
            https://docs.rs/humantime/latest/humantime/fn.parse_duration.html
            for more details
        endpoint : builtins.str, optional
            network address of the Redis service.
            Can be "tcp://127.0.0.1:6379", e.g.
            default is "tcp://127.0.0.1:6379"
        password : builtins.str, optional
            the password for authentication default is None
        root : builtins.str, optional
            the working directory of the Redis service.
            Can be "/path/to/dir" default is "/"
        username : builtins.str, optional
            the username to connect redis service.
            default is None

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `redis` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Seafile | typing.Literal["seafile"],
        /,
        *,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        repo_name: builtins.str,
        root: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `seafile` service.

        Parameters
        ----------
        endpoint : builtins.str, optional
            endpoint address of this backend.
        password : builtins.str, optional
            password of this backend.
        repo_name : builtins.str
            repo_name of this backend.
            required.
        root : builtins.str, optional
            root of this backend.
            All operations will happen under this root.
        username : builtins.str, optional
            username of this backend.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `seafile` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Sftp | typing.Literal["sftp"],
        /,
        *,
        enable_copy: builtins.bool = ...,
        endpoint: builtins.str = ...,
        key: builtins.str = ...,
        known_hosts_strategy: builtins.str = ...,
        root: builtins.str = ...,
        user: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `sftp` service.

        Parameters
        ----------
        enable_copy : builtins.bool, optional
            enable_copy of this backend
        endpoint : builtins.str, optional
            endpoint of this backend
        key : builtins.str, optional
            key of this backend
        known_hosts_strategy : builtins.str, optional
            known_hosts_strategy of this backend
        root : builtins.str, optional
            root of this backend
        user : builtins.str, optional
            user of this backend

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `sftp` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Swift | typing.Literal["swift"],
        /,
        *,
        container: builtins.str = ...,
        endpoint: builtins.str = ...,
        root: builtins.str = ...,
        token: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `swift` service.

        Parameters
        ----------
        container : builtins.str, optional
            The container for Swift.
        endpoint : builtins.str, optional
            The endpoint for Swift.
        root : builtins.str, optional
            The root for Swift.
        token : builtins.str, optional
            The token for Swift.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `swift` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.VercelArtifacts
        | typing.Literal["vercel-artifacts"],
        /,
        *,
        access_token: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `vercel-artifacts` service.

        Parameters
        ----------
        access_token : builtins.str, optional
            The access token for Vercel.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `vercel-artifacts` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Webdav | typing.Literal["webdav"],
        /,
        *,
        disable_copy: builtins.bool = ...,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        root: builtins.str = ...,
        token: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `webdav` service.

        Parameters
        ----------
        disable_copy : builtins.bool, optional
            WebDAV Service doesn't support copy.
        endpoint : builtins.str, optional
            endpoint of this backend
        password : builtins.str, optional
            password of this backend
        root : builtins.str, optional
            root of this backend
        token : builtins.str, optional
            token of this backend
        username : builtins.str, optional
            username of this backend

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `webdav` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Webhdfs | typing.Literal["webhdfs"],
        /,
        *,
        atomic_write_dir: builtins.str = ...,
        delegation: builtins.str = ...,
        disable_list_batch: builtins.bool = ...,
        endpoint: builtins.str = ...,
        root: builtins.str = ...,
        user_name: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `webhdfs` service.

        Parameters
        ----------
        atomic_write_dir : builtins.str, optional
            atomic_write_dir of this backend
        delegation : builtins.str, optional
            Delegation token for webhdfs.
        disable_list_batch : builtins.bool, optional
            Disable batch listing
        endpoint : builtins.str, optional
            Endpoint for webhdfs.
        root : builtins.str, optional
            Root for webhdfs.
        user_name : builtins.str, optional
            Name of the user for webhdfs.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `webhdfs` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.YandexDisk | typing.Literal["yandex-disk"],
        /,
        *,
        access_token: builtins.str,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `AsyncOperator` for `yandex-disk` service.

        Parameters
        ----------
        access_token : builtins.str
            yandex disk oauth access_token.
        root : builtins.str, optional
            root of this backend.
            All operations will happen under this root.

        Returns
        -------
        AsyncOperator
            The new `AsyncOperator` for `yandex-disk` service
        """

@typing.final
class Operator:
    r"""
    The blocking equivalent of `AsyncOperator`.

    `Operator` is the entry point for all blocking APIs.

    See Also
    --------
    AsyncOperator
    """

    def layer(self, layer: Layer) -> Operator:
        r"""
        Add a new layer to this operator.

        Parameters
        ----------
        layer : Layer
            The layer to add.

        Returns
        -------
        Operator
            A new operator with the layer added.
        """
    def open(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        mode: builtins.str,
        **kwargs: typing.Any,
    ) -> File:
        r"""
        Open a file-like object for the given path.

        The returning file-like object is a context manager.

        Parameters
        ----------
        path : str
            The path to the file.
        mode : str
            The mode to open the file in. Only "rb" and "wb" are supported.
        **kwargs
            Additional options for the underlying reader or writer.

        Returns
        -------
        File
            A file-like object.
        """
    def read(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        *,
        version: builtins.str | None = None,
        concurrent: builtins.int | None = None,
        chunk: builtins.int | None = None,
        gap: builtins.int | None = None,
        offset: builtins.int | None = None,
        prefetch: builtins.int | None = None,
        size: builtins.int | None = None,
        if_match: builtins.str | None = None,
        if_none_match: builtins.str | None = None,
        if_modified_since: datetime.datetime = None,
        if_unmodified_since: datetime.datetime = None,
        content_type: builtins.str | None = None,
        cache_control: builtins.str | None = None,
        content_disposition: builtins.str | None = None,
    ) -> builtins.bytes:
        r"""
        Read the entire contents of a file at the given path.

        Parameters
        ----------
        path : str
            The path to the file.
        version : str, optional
            The version of the file.
        concurrent : int, optional
            The number of concurrent readers.
        chunk : int, optional
            The size of each chunk.
        gap : int, optional
            The gap between each chunk.
        offset : int, optional
            The offset of the file.
        prefetch : int, optional
            The number of bytes to prefetch.
        size : int, optional
            The size of the file.
        if_match : str, optional
            The ETag of the file.
        if_none_match : str, optional
            The ETag of the file.
        if_modified_since : str, optional
            The last modified time of the file.
        if_unmodified_since : str, optional
            The last modified time of the file.
        content_type : str, optional
            The content type of the file.
        cache_control : str, optional
            The cache control of the file.
        content_disposition : str, optional
            The content disposition of the file.

        Returns
        -------
        bytes
            The contents of the file as bytes.
        """
    def write(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        bs: builtins.bytes,
        *,
        append: builtins.bool | None = None,
        chunk: builtins.int | None = None,
        concurrent: builtins.int | None = None,
        cache_control: builtins.str | None = None,
        content_type: builtins.str | None = None,
        content_disposition: builtins.str | None = None,
        content_encoding: builtins.str | None = None,
        if_match: builtins.str | None = None,
        if_none_match: builtins.str | None = None,
        if_not_exists: builtins.bool | None = None,
        user_metadata: typing.Mapping[builtins.str, builtins.str] | None = None,
    ) -> None:
        r"""
        Write bytes to a file at the given path.

        This function will create a file if it does not exist, and will
        overwrite its contents if it does.

        Parameters
        ----------
        path : str
            The path to the file.
        bs : bytes
            The contents to write to the file.
        append : bool, optional
            Whether to append to the file instead of overwriting it.
        chunk : int, optional
            The chunk size to use when writing the file.
        concurrent : int, optional
            The number of concurrent requests to make when writing the file.
        cache_control : str, optional
            The cache control header to set on the file.
        content_type : str, optional
            The content type header to set on the file.
        content_disposition : str, optional
            The content disposition header to set on the file.
        content_encoding : str, optional
            The content encoding header to set on the file.
        if_match : str, optional
            The ETag to match when writing the file.
        if_none_match : str, optional
            The ETag to not match when writing the file.
        if_not_exists : bool, optional
            Whether to fail if the file already exists.
        user_metadata : dict, optional
            The user metadata to set on the file.
        """
    def stat(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        *,
        version: builtins.str | None = None,
        if_match: builtins.str | None = None,
        if_none_match: builtins.str | None = None,
        if_modified_since: datetime.datetime = None,
        if_unmodified_since: datetime.datetime = None,
        content_type: builtins.str | None = None,
        cache_control: builtins.str | None = None,
        content_disposition: builtins.str | None = None,
    ) -> Metadata:
        r"""
        Get the metadata of a file at the given path.

        Parameters
        ----------
        path : str
            The path to the file.
        version : str, optional
            The version of the file.
        if_match : str, optional
            The ETag of the file.
        if_none_match : str, optional
            The ETag of the file.
        if_modified_since : datetime, optional
            The last modified time of the file.
        if_unmodified_since : datetime, optional
            The last modified time of the file.
        content_type : str, optional
            The content type of the file.
        cache_control : str, optional
            The cache control of the file.
        content_disposition : str, optional
            The content disposition of the file.

        Returns
        -------
        Metadata
            The metadata of the file.
        """
    def copy(
        self,
        source: builtins.str | os.PathLike | pathlib.Path,
        target: builtins.str | os.PathLike | pathlib.Path,
    ) -> None:
        r"""
        Copy a file from one path to another.

        Parameters
        ----------
        source : str
            The path to the source file.
        target : str
            The path to the target file.
        """
    def rename(
        self,
        source: builtins.str | os.PathLike | pathlib.Path,
        target: builtins.str | os.PathLike | pathlib.Path,
    ) -> None:
        r"""
        Rename (move) a file from one path to another.

        Parameters
        ----------
        source : str
            The path to the source file.
        target : str
            The path to the target file.
        """
    def remove_all(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Recursively remove all files and directories at the given path.

        Parameters
        ----------
        path : str
            The path to remove.
        """
    def create_dir(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Create a directory at the given path.

        Notes
        -----
        To indicate that a path is a directory, it must end with a `/`.
        This operation is always recursive, like `mkdir -p`.

        Parameters
        ----------
        path : str
            The path to the directory.
        """
    def delete(self, path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Delete a file at the given path.

        Notes
        -----
        This operation will not return an error if the path does not exist.

        Parameters
        ----------
        path : str
            The path to the file.
        """
    def exists(self, path: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool:
        r"""
        Check if a path exists.

        Parameters
        ----------
        path : str
            The path to check.

        Returns
        -------
        bool
            True if the path exists, False otherwise.
        """
    def list(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        *,
        limit: builtins.int | None = None,
        start_after: builtins.str | None = None,
        recursive: builtins.bool | None = None,
        versions: builtins.bool | None = None,
        deleted: builtins.bool | None = None,
    ) -> collections.abc.Iterable[opendal.types.Entry]:
        r"""
        List entries in the given directory.

        Parameters
        ----------
        path : str
            The path to the directory.
        limit : int, optional
            The maximum number of entries to return.
        start_after : str, optional
            The entry to start after.
        recursive : bool, optional
            Whether to list recursively.
        versions : bool, optional
            Whether to list versions.
        deleted : bool, optional
            Whether to list deleted entries.

        Returns
        -------
        BlockingLister
            An iterator over the entries in the directory.
        """
    def scan(
        self,
        path: builtins.str | os.PathLike | pathlib.Path,
        *,
        limit: builtins.int | None = None,
        start_after: builtins.str | None = None,
        versions: builtins.bool | None = None,
        deleted: builtins.bool | None = None,
    ) -> collections.abc.Iterable[opendal.types.Entry]:
        r"""
        Recursively list entries in the given directory.

        Deprecated
        ----------
            Use `list()` with `recursive=True` instead.

        Parameters
        ----------
        path : str
            The path to the directory.
        limit : int, optional
            The maximum number of entries to return.
        start_after : str, optional
            The entry to start after.
        versions : bool, optional
            Whether to list versions.
        deleted : bool, optional
            Whether to list deleted entries.

        Returns
        -------
        BlockingLister
            An iterator over the entries in the directory.
        """
    def capability(self) -> Capability:
        r"""
        Get all capabilities of this operator.

        Returns
        -------
        Capability
            The capability of the operator.
        """
    def check(self) -> None:
        r"""
        Check if the operator is able to work correctly.

        Raises
        ------
        Exception
            If the operator is not able to work correctly.
        """
    def to_async_operator(self) -> AsyncOperator:
        r"""
        Create a new `AsyncOperator` from this blocking operator.

        Returns
        -------
        AsyncOperator
            The async operator.
        """
    @typing.overload
    def __new__(
        cls, scheme: builtins.str, /, **kwargs: builtins.str
    ) -> typing_extensions.Self: ...
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Gdrive | typing.Literal["gdrive"],
        /,
        *,
        access_token: builtins.str = ...,
        client_id: builtins.str = ...,
        client_secret: builtins.str = ...,
        refresh_token: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `gdrive` service.

        Parameters
        ----------
        access_token : builtins.str, optional
            Access token for gdrive.
        client_id : builtins.str, optional
            Client id for gdrive.
        client_secret : builtins.str, optional
            Client secret for gdrive.
        refresh_token : builtins.str, optional
            Refresh token for gdrive.
        root : builtins.str, optional
            The root for gdrive

        Returns
        -------
        Operator
            The new `Operator` for `gdrive` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Gridfs | typing.Literal["gridfs"],
        /,
        *,
        bucket: builtins.str = ...,
        chunk_size: builtins.int = ...,
        connection_string: builtins.str = ...,
        database: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `gridfs` service.

        Parameters
        ----------
        bucket : builtins.str, optional
            The bucket name of the MongoDB GridFs service to
            read/write.
        chunk_size : builtins.int, optional
            The chunk size of the MongoDB GridFs service used to
            break the user file into chunks.
        connection_string : builtins.str, optional
            The connection string of the MongoDB service.
        database : builtins.str, optional
            The database name of the MongoDB GridFs service to
            read/write.
        root : builtins.str, optional
            The working directory, all operations will be
            performed under it.

        Returns
        -------
        Operator
            The new `Operator` for `gridfs` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Http | typing.Literal["http"],
        /,
        *,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        root: builtins.str = ...,
        token: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `http` service.

        Parameters
        ----------
        endpoint : builtins.str, optional
            endpoint of this backend
        password : builtins.str, optional
            password of this backend
        root : builtins.str, optional
            root of this backend
        token : builtins.str, optional
            token of this backend
        username : builtins.str, optional
            username of this backend

        Returns
        -------
        Operator
            The new `Operator` for `http` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Ipmfs | typing.Literal["ipmfs"],
        /,
        *,
        endpoint: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `ipmfs` service.

        Parameters
        ----------
        endpoint : builtins.str, optional
            Endpoint for ipfs.
        root : builtins.str, optional
            Root for ipfs.

        Returns
        -------
        Operator
            The new `Operator` for `ipmfs` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Memory | typing.Literal["memory"],
        /,
        *,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `memory` service.

        Parameters
        ----------
        root : builtins.str, optional
            root of the backend.

        Returns
        -------
        Operator
            The new `Operator` for `memory` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Mongodb | typing.Literal["mongodb"],
        /,
        *,
        collection: builtins.str = ...,
        connection_string: builtins.str = ...,
        database: builtins.str = ...,
        key_field: builtins.str = ...,
        root: builtins.str = ...,
        value_field: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `mongodb` service.

        Parameters
        ----------
        collection : builtins.str, optional
            collection of this backend
        connection_string : builtins.str, optional
            connection string of this backend
        database : builtins.str, optional
            database of this backend
        key_field : builtins.str, optional
            key field of this backend
        root : builtins.str, optional
            root of this backend
        value_field : builtins.str, optional
            value field of this backend

        Returns
        -------
        Operator
            The new `Operator` for `mongodb` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Onedrive | typing.Literal["onedrive"],
        /,
        *,
        access_token: builtins.str = ...,
        client_id: builtins.str = ...,
        client_secret: builtins.str = ...,
        enable_versioning: builtins.bool = ...,
        refresh_token: builtins.str = ...,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `onedrive` service.

        Parameters
        ----------
        access_token : builtins.str, optional
            Microsoft Graph API (also OneDrive API) access token
        client_id : builtins.str, optional
            Microsoft Graph API Application (client) ID that is
            in the Azure's app registration portal
        client_secret : builtins.str, optional
            Microsoft Graph API Application client secret that
            is in the Azure's app registration portal
        enable_versioning : builtins.bool, optional
            Enabling version support
        refresh_token : builtins.str, optional
            Microsoft Graph API (also OneDrive API) refresh
            token
        root : builtins.str, optional
            The root path for the OneDrive service for the file
            access

        Returns
        -------
        Operator
            The new `Operator` for `onedrive` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Redis | typing.Literal["redis"],
        /,
        *,
        cluster_endpoints: builtins.str = ...,
        connection_pool_max_size: builtins.int = ...,
        db: builtins.int,
        default_ttl: typing.Any = ...,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        root: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `redis` service.

        Parameters
        ----------
        cluster_endpoints : builtins.str, optional
            network address of the Redis cluster service.
            Can be
            "tcp://127.0.0.1:6379,tcp://127.0.0.1:6380,tcp://127.0.0.1:6381",
            e.g.
            default is None
        connection_pool_max_size : builtins.int, optional
            The maximum number of connections allowed.
            default is 10
        db : builtins.int
            the number of DBs redis can take is unlimited
            default is db 0
        default_ttl : typing.Any, optional
            The default ttl for put operations..
            a human readable duration string see
            https://docs.rs/humantime/latest/humantime/fn.parse_duration.html
            for more details
        endpoint : builtins.str, optional
            network address of the Redis service.
            Can be "tcp://127.0.0.1:6379", e.g.
            default is "tcp://127.0.0.1:6379"
        password : builtins.str, optional
            the password for authentication default is None
        root : builtins.str, optional
            the working directory of the Redis service.
            Can be "/path/to/dir" default is "/"
        username : builtins.str, optional
            the username to connect redis service.
            default is None

        Returns
        -------
        Operator
            The new `Operator` for `redis` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Seafile | typing.Literal["seafile"],
        /,
        *,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        repo_name: builtins.str,
        root: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `seafile` service.

        Parameters
        ----------
        endpoint : builtins.str, optional
            endpoint address of this backend.
        password : builtins.str, optional
            password of this backend.
        repo_name : builtins.str
            repo_name of this backend.
            required.
        root : builtins.str, optional
            root of this backend.
            All operations will happen under this root.
        username : builtins.str, optional
            username of this backend.

        Returns
        -------
        Operator
            The new `Operator` for `seafile` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Sftp | typing.Literal["sftp"],
        /,
        *,
        enable_copy: builtins.bool = ...,
        endpoint: builtins.str = ...,
        key: builtins.str = ...,
        known_hosts_strategy: builtins.str = ...,
        root: builtins.str = ...,
        user: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `sftp` service.

        Parameters
        ----------
        enable_copy : builtins.bool, optional
            enable_copy of this backend
        endpoint : builtins.str, optional
            endpoint of this backend
        key : builtins.str, optional
            key of this backend
        known_hosts_strategy : builtins.str, optional
            known_hosts_strategy of this backend
        root : builtins.str, optional
            root of this backend
        user : builtins.str, optional
            user of this backend

        Returns
        -------
        Operator
            The new `Operator` for `sftp` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Swift | typing.Literal["swift"],
        /,
        *,
        container: builtins.str = ...,
        endpoint: builtins.str = ...,
        root: builtins.str = ...,
        token: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `swift` service.

        Parameters
        ----------
        container : builtins.str, optional
            The container for Swift.
        endpoint : builtins.str, optional
            The endpoint for Swift.
        root : builtins.str, optional
            The root for Swift.
        token : builtins.str, optional
            The token for Swift.

        Returns
        -------
        Operator
            The new `Operator` for `swift` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.VercelArtifacts
        | typing.Literal["vercel-artifacts"],
        /,
        *,
        access_token: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `vercel-artifacts` service.

        Parameters
        ----------
        access_token : builtins.str, optional
            The access token for Vercel.

        Returns
        -------
        Operator
            The new `Operator` for `vercel-artifacts` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Webdav | typing.Literal["webdav"],
        /,
        *,
        disable_copy: builtins.bool = ...,
        endpoint: builtins.str = ...,
        password: builtins.str = ...,
        root: builtins.str = ...,
        token: builtins.str = ...,
        username: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `webdav` service.

        Parameters
        ----------
        disable_copy : builtins.bool, optional
            WebDAV Service doesn't support copy.
        endpoint : builtins.str, optional
            endpoint of this backend
        password : builtins.str, optional
            password of this backend
        root : builtins.str, optional
            root of this backend
        token : builtins.str, optional
            token of this backend
        username : builtins.str, optional
            username of this backend

        Returns
        -------
        Operator
            The new `Operator` for `webdav` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.Webhdfs | typing.Literal["webhdfs"],
        /,
        *,
        atomic_write_dir: builtins.str = ...,
        delegation: builtins.str = ...,
        disable_list_batch: builtins.bool = ...,
        endpoint: builtins.str = ...,
        root: builtins.str = ...,
        user_name: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `webhdfs` service.

        Parameters
        ----------
        atomic_write_dir : builtins.str, optional
            atomic_write_dir of this backend
        delegation : builtins.str, optional
            Delegation token for webhdfs.
        disable_list_batch : builtins.bool, optional
            Disable batch listing
        endpoint : builtins.str, optional
            Endpoint for webhdfs.
        root : builtins.str, optional
            Root for webhdfs.
        user_name : builtins.str, optional
            Name of the user for webhdfs.

        Returns
        -------
        Operator
            The new `Operator` for `webhdfs` service
        """
    @typing.overload
    def __new__(
        cls,
        scheme: opendal.services.Scheme.YandexDisk | typing.Literal["yandex-disk"],
        /,
        *,
        access_token: builtins.str,
        root: builtins.str = ...,
    ) -> typing_extensions.Self:
        r"""
        Create a new `Operator` for `yandex-disk` service.

        Parameters
        ----------
        access_token : builtins.str
            yandex disk oauth access_token.
        root : builtins.str, optional
            root of this backend.
            All operations will happen under this root.

        Returns
        -------
        Operator
            The new `Operator` for `yandex-disk` service
        """
