# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Setup Rust Builder
description: 'Prepare Rust Build Environment'

runs:
  using: "composite"
  steps:
    - name: Setup rust related environment variables
      shell: bash
      run: |
        # Update rust to latest stable
        rustup update stable
        # Disable full debug symbol generation to speed up CI build and keep memory down
        # "1" means line tables only, which is useful for panic tracebacks.
        echo "RUSTFLAGS=-C debuginfo=1" >> $GITHUB_ENV
        # Enable backtraces
        echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        # Enable logging
        echo "RUST_LOG=debug" >> $GITHUB_ENV
        # Enable sparse index
        echo "CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse" >> $GITHUB_ENV

    - name: Setup rust on linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Set rocksdb lib path
        echo "ROCKSDB_LIB_DIR=/tmp/rocksdb" >> $GITHUB_ENV

    - name: Cache Cargo
      uses: actions/cache@v3
      if: runner.os == 'Linux'
      with:
        path: /tmp/rocksdb
        key: r0-rocksdb-8.1.1
        restore-keys: |
          r0-rocksdb-

    - name: Build rocksdb if not cached
      if: steps.cache-primes.outputs.cache-hit != 'true' && runner.os == 'Linux'
      shell: bash
      run: |
        set -e

        sudo apt-get install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

        cd /tmp
        curl https://github.com/facebook/rocksdb/archive/refs/tags/v8.1.1.tar.gz -L -o rocksdb.tar.gz
        tar -xzf rocksdb.tar.gz
        cd rocksdb-8.1.1

        mkdir /tmp/rocksdb
        cmake -DCMAKE_INSTALL_PREFIX=/tmp/rocksdb
        make -j$(nproc)
        make install-static

        cd ..
        rm -rf /tmp/rocksdb-8.1.1
