#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

SCRIPT_PATH="$(cd "$(dirname $(realpath "$0"))" >/dev/null 2>&1 && pwd)"
REL_PATH="$(realpath `pwd` --relative-base=${SCRIPT_PATH})"

CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
COMMAND="$@"

# NOTE: create with runner user first to avoid permission issues
mkdir -p "${CARGO_HOME}/registry"

_UID=$(id -u)
if [[ ${_UID} != "501" ]] && [[ $_UID != "1000" ]] && [[ $_UID != "1001" ]]; then
	echo "warning: You might encounter permission issues when running this script, since the current uid is ${_UID}, not in [501,1000,1001]." >&2
	echo ":) feel free to ignore this warning if you do not need sudo." >&2
fi

exec docker run --rm --tty --net=host \
    --interactive \
    --env TERM=xterm-256color \
	--user $(id -u):$(id -g) \
	--volume "${CARGO_HOME}/registry:/opt/rust/cargo/registry" \
	--volume "${SCRIPT_PATH}:/workspace" \
	--workdir "/workspace/${REL_PATH}" \
	"ghcr.io/apache/opendal-devtools:latest" \
	/bin/bash -c "${COMMAND}"
