name: 'Check'
description: 'Check will do all essential checks'
inputs:
  github_token:
    description: "Github Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Format
      shell: bash
      run: cargo fmt --all -- --check

    - name: Doc check
      shell: bash
      run: cargo doc --no-deps

    - name: Check License Header
      uses: apache/skywalking-eyes/header@main
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        log: info

    - name: Install cargo-audit
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-audit

    - name: Audit dependencies
      shell: bash
      run: cargo audit

    - name: Clippy
      shell: bash
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Clippy Oli
      shell: bash
      working-directory: ./oli
      run: cargo clippy --all-targets --all-features -- -D warnings
