class Operator:
    def __init__(scheme: str, **kwargs): ...
    def read(self, path: str) -> bytes: ...
    def write(self, path: str, bs: bytes): ...
    def stat(self, path: str) -> Metadata: ...

class AsyncOperator:
    def __init__(scheme: str, **kwargs): ...
    async def read(self, path: str) -> bytes: ...
    async def write(self, path: str, bs: bytes): ...
    async def stat(self, path: str) -> Metadata: ...

class Metadata:
    @property
    def content_length(self) -> int: ...
