# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: cos
description: "Behavior test for COS. This service is sponsored by @datafuse_labs."

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: 1Password/load-secrets-action@92467eb28f72e8255933372f1e0707c567ce2259 # v4.0.0
      with:
        export-env: true
      env:
        OPENDAL_COS_BUCKET: op://services/cos/bucket
        OPENDAL_COS_ENDPOINT: op://services/cos/endpoint
        OPENDAL_COS_SECRET_ID: op://services/cos/secret_id
        OPENDAL_COS_SECRET_KEY: op://services/cos/secret_key

    - name: Add extra settings
      shell: bash
      run: |
        echo "OPENDAL_TEST_CAPABILITY_OVERRIDES=write_with_if_not_exists=false,copy_with_if_not_exists=false" >> $GITHUB_ENV
