# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "edge_test_opfs_on_wasm"

edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1.0.30", features = ["std"] }
bytes = "1.6"
futures = "0.3"
opendal = { path = "../..", default-features = false, features = [
  "services-opfs",
] }
rand = { version = "0.8" }
sha2 = "0.10"
uuid = { version = "1", features = ["serde", "v4"] }

wasm-bindgen-test = "0.3.41"
