# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

import os

if __name__ == "__main__":
    GITHUB_WORKSPACE = os.environ.get("GITHUB_WORKSPACE")
    SERVICE = os.environ.get("SERVICE")
    if not GITHUB_WORKSPACE or not SERVICE:
        raise ValueError("GITHUB_WORKSPACE and SERVICE must be set")
    with open(GITHUB_WORKSPACE + "/bindings/go/tests/behavior_tests/scheme_test.go", "w") as f:
        f.write(f"""// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// generated by github.com/apache/opendal/bindings/go

package opendal_test

import (
	opendal "github.com/apache/opendal/bindings/go"
    "github.com/apache/opendal-go-services/{SERVICE}"
)

// Add more schemes for behavior tests here.
var schemes = []opendal.Scheme{{
    {SERVICE}.Scheme,
}}""")

