# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Service Test Sftp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "core/src/**"
      - "core/tests/**"
      - "!core/src/docs/**"
      - "!core/src/services/**"
      - "core/src/services/sftp/**"
      - ".github/workflows/service_test_sftp.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  sftp-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sftp
        run: |
          mkdir -p target/ssh
          ssh-keygen -t rsa -b 4096 -f target/ssh/id_rsa -q -N "" < /dev/null
          docker run \
              -v `pwd`/target/ssh/id_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro \
              --ulimit nofile=65536:65536 \
              -p 2222:22 -d atmoz/sftp \
              foo::::upload
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          need-nextest: true
      - name: Test
        shell: bash
        timeout-minutes: 10
        working-directory: core
        run: cargo nextest run sftp --features services-sftp
        env:
          OPENDAL_SFTP_TEST: on
          OPENDAL_SFTP_ENDPOINT: ssh://127.0.0.1:2222
          OPENDAL_SFTP_ROOT: /upload/sftp_test/
          OPENDAL_SFTP_USER: foo
          OPENDAL_SFTP_KEY: ${{ github.workspace }}/target/ssh/id_rsa
          OPENDAL_SFTP_KNOWN_HOSTS_STRATEGY: accept

  sftp-test-default-root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sftp
        run: |
          mkdir -p target/ssh
          ssh-keygen -t rsa -b 4096 -f target/ssh/id_rsa -q -N "" < /dev/null
          tmpScript="$(mktemp)"
          echo "sed -i -e 's#ForceCommand internal-sftp#ForceCommand internal-sftp -d /upload#' /etc/ssh/sshd_config" > "$tmpScript"
          chmod +x "$tmpScript"
          docker run \
              -v "$tmpScript:/etc/sftp.d/change_root_dir" \
              -v `pwd`/target/ssh/id_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro \
              --ulimit nofile=65536:65536 \
              -p 2222:22 -d atmoz/sftp \
              foo::::upload
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          need-nextest: true
      - name: Test
        shell: bash
        timeout-minutes: 10
        working-directory: core
        run: cargo nextest run sftp --features services-sftp
        env:
          OPENDAL_SFTP_TEST: on
          OPENDAL_SFTP_ENDPOINT: ssh://127.0.0.1:2222
          OPENDAL_SFTP_USER: foo
          OPENDAL_SFTP_KEY: ${{ github.workspace }}/target/ssh/id_rsa
          OPENDAL_SFTP_KNOWN_HOSTS_STRATEGY: accept
          OPENDAL_DISABLE_RANDOM_ROOT: true